services:
  mysql:
    image: mysql:8.0
    container_name: banking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: postmig#2020
      MYSQL_DATABASE: banking_db
    ports:
      - "3306:3306"

  redis:
    image: redis:7.0
    container_name: banking-redis
    ports:
      - "6379:6379"

  transaction-service:
    image: transaction-service:latest
    container_name: banking-transaction-service
    ports:
      - "8083:8083"
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: postmig#2020
     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
     ACCOUNT_SERVICE_URL: http://account-service-9092
    depends_on:
      - mysql
      - kafka
      - account-service




  account-service:
    image: account-service:latest
    container_name: banking-account-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postmig#2020
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      USER_SERVICE_URL: http://user-service:8081
    depends_on:
      - mysql
      - kafka
      - user-service

  user-service:
    image: user-service:latest
    container_name: banking-user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: postmig#2020
      SPRING_DATA_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - mysql
      - redis
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: banking-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: banking-kafka
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
