spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/banking_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: postmig#2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: myBankingAppSuperSecretKeyForJWT2024MustBe32Chars
  expiration: 86400000